#!/usr/bin/env python3
"""Build the Java 5 API index that check-bdj-java5.py verifies against.

There is no free-licensed Java 5 class library to vendor the way
contrib/java6-bootclasspath holds OpenJDK 6's rt.jar: OpenJDK only started at
Java 6, and the alternatives that do cover Java 5 (Apache Harmony, GNU
Classpath) reimplement the platform without Sun's internals -- which is exactly
what the BD-J adaptation layer plugs into (java.io.FileSystem,
java.awt.peer.*, sun.awt.*), so they cannot answer the question being asked.

What the check actually needs is not the class library but a list of what it
declares: class names, the hierarchy, and member name/descriptor pairs. This
script extracts that from a real Java 5 JRE into a compact text index, which is
what gets committed. No implementation is copied, which is the same shape as the
per-release API data a JDK ships in ct.sym.

    make-java5-api-index.py -o contrib/java5-api/<name>.txt.gz JAR [JAR...]

Run it once against a Mac OS X 10.4/10.5 install:

    /System/Library/Frameworks/JavaVM.framework/Versions/1.5/Classes/*.jar

Format, one record per line, classes introducing the members that follow:

    C <class> <superclass|-> [<interface>,...]
    F <name> <descriptor>
    M <name> <descriptor>
"""

import argparse
import gzip
import importlib.util
import os
import sys
import zipfile

_HERE = os.path.dirname(os.path.abspath(__file__))
_spec = importlib.util.spec_from_file_location(
    'check_bdj_java6', os.path.join(_HERE, 'check-bdj-java6.py'))
_j6 = importlib.util.module_from_spec(_spec)
_no_bytecode = sys.dont_write_bytecode
sys.dont_write_bytecode = True
try:
    _spec.loader.exec_module(_j6)
finally:
    sys.dont_write_bytecode = _no_bytecode


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('jars', nargs='+', metavar='JAR')
    parser.add_argument('-o', '--output', required=True)
    parser.add_argument('--source', default='',
                        help='provenance recorded in the index header')
    args = parser.parse_args()

    classes = {}
    for path in args.jars:
        with zipfile.ZipFile(path) as zf:
            for entry in zf.namelist():
                if not entry.endswith('.class'):
                    continue
                try:
                    cf = _j6.ClassFile(zf.read(entry))
                except (ValueError, IndexError, KeyError):
                    continue
                classes.setdefault(cf.name, cf)

    out = []
    if args.source:
        out.append('# %s' % args.source)
    out.append('# generated by make-java5-api-index.py; do not edit by hand')
    for name in sorted(classes):
        cf = classes[name]
        out.append('C %s %s %s' % (name, cf.super or '-',
                                   ','.join(sorted(cf.interfaces))))
        for mname, desc in sorted(cf.fields):
            out.append('F %s %s' % (mname, desc))
        for mname, desc in sorted(cf.methods):
            out.append('M %s %s' % (mname, desc))

    blob = ('\n'.join(out) + '\n').encode('utf-8')
    # mtime=0 so regenerating an unchanged index produces an identical file.
    with open(args.output, 'wb') as fh:
        with gzip.GzipFile(fileobj=fh, mode='wb', mtime=0) as gz:
            gz.write(blob)
    print('%d classes -> %s (%d bytes)'
          % (len(classes), args.output, os.path.getsize(args.output)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
